name: Deploy to Server

on:
push:
    branches:
    - main

jobs:
build-and-deploy:
    runs-on: ubuntu-latest
    environment: server_config

    steps:
    - name: Checkout code
    uses: actions/checkout@v3

    - name: Deploy to remote server
    uses: appleboy/ssh-action@v0.1.5
    with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: echo "hi"